---
title: 'STAT 540 - Seminar 2b: Graphing using ggplot2'
author: "Fariha Khan"
date: '2018-01-10'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


## The mpg data frame

```{r mpg}
mpg
```

## Creating a ggplot

You can also embed plots, for example:

```{r pressure, echo=FALSE}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
ggplot(data = mpg) + 
      geom_point(mapping = aes(x = displ, y = hwy, size = class))
```

## Part 2: The layered grammar

```{r}
apropos("^geom_")
apropos("^stat_")
apropos("^scale_")
```

```{r smooth line}
ggplot(data = mpg, 
       mapping = aes(x = displ, y = hwy)) +
  geom_point() +
  geom_smooth()
```

## Part 3: Deliverable
```{r deliverable}
ggplot(data = mpg, 
       mapping = aes(x = displ, y = hwy)) +
  geom_point(aes(size = class, color = drv)) 
```

